// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfApp;

#nullable disable

namespace WpfApp.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20221119030234_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("WpfApp.ByteImage", b =>
                {
                    b.Property<int>("imageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("byteImage")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("imageID");

                    b.ToTable("ByteImages");
                });

            modelBuilder.Entity("WpfApp.Hash", b =>
                {
                    b.Property<int>("imageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("hash")
                        .HasColumnType("INTEGER");

                    b.HasKey("imageID");

                    b.ToTable("Hashes");
                });

            modelBuilder.Entity("WpfApp.Image", b =>
                {
                    b.Property<int>("imageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("imageID");

                    b.ToTable("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
